# Generated by Django 3.2.13 on 2022-07-13 11:30

import apps.company.blocks.header
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20220618_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', apps.company.blocks.header.HeadingBlock())], default=None),
        ),
    ]
