
on:
  push:
    branches:
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

name: CI | don
jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10.5
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.5

      - name: Install Linux Dependencies
        run: sudo apt-get install libpq-dev libxml2-dev -y

      - uses: actions/checkout@v3
        name: Git Checkout
        with:
          fetch-depth: 0

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip coverage
          cd core
          pip install -r requirements.txt

      - name: Executing tests
        id: test
        working-directory: core
        run: |
            coverage run manage.py test --noinput -v 2

      - name: Generate XML
        run: |
          cd core
          coverage xml
          sed -i 's;/home/runner/work/wagsshit/wagsshit/;/github/workspace/;g' .coverage-reports/coverage-report.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
