
on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

name: CIdon
jobs:
  build:
    name: Build & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Linux Dependencies
        run: sudo apt-get install libpq-dev libxml2-dev -y

      - uses: actions/checkout@v3
        name: Git Checkout
        with:
          fetch-depth: 0

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip poetry converage
          poetry add

      - name: Executing tests
        id: test
        working-directory: core
        run: |
            coverage run manage.py test apps.model_admin --noinput --verbose

      - name: Generate XML
        run: |
          cd core
          coverage xml

  sonarcloud:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
